server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location /generate-password {
        proxy_pass http://api-gateway:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /health {
        proxy_pass http://api-gateway:8080;
        proxy_set_header Host $host;
    }

    location /metrics {
        proxy_pass http://api-gateway:8080;
        proxy_set_header Host $host;
    }

    location /policy-health {
        proxy_pass http://api-gateway:8080;
        proxy_set_header Host $host;
    }

    location /history-health {
        proxy_pass http://api-gateway:8080;
        proxy_set_header Host $host;
    }

    location / {
        try_files $uri /index.html;
    }
}
