receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
  docker_stats:
    endpoint: unix:///var/run/docker.sock
    collection_interval: 10s
    timeout: 20s
  redis:
    endpoint: redis:6379
    collection_interval: 10s

processors:
  batch:

exporters:
  otlp/elastic:
    endpoint: edot-collector:4317
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/elastic]
    metrics:
      receivers: [otlp, docker_stats, redis]
      processors: [batch]
      exporters: [otlp/elastic]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/elastic]
